pipeline {
	agent any
	
    stages {
        stage('Build') {
	    steps {
               sh "mvn -f moodprism/pom.xml clean -DskipTests package"
            }
        }
        
        stage('Test') {
            steps {
	       sh "mvn -f moodprism/pom.xml test"
            }
        }
	/*stage('Deploy') {
	    steps {
		sh 'mvn -f moodprism/pom.xml deploy -s moodprism/settings.xml'
	    }
	}
	stage('Build Docker Image'){
	    steps{
		    dir('moodprism'){
		       sh 'docker image rm esp10-moodprism'
		       sh 'docker build -t esp10-moodprism .'
		       sh 'docker tag esp10-moodprism 192.168.160.99:5000/esp10-moodprism'
		       sh 'docker push 192.168.160.99:5000/esp10-moodprism'
		       //sh 'docker images'
		    }
	    }
	}
	stage('Deploy runtime'){
	   steps{
		 dir('moodprism'){
	             sshagent(credentials:['esp10_ssh_runtimeVM']){
			sh 'ssh -o StrictHostKeyChecking=no esp10@192.168.160.103 docker run --rm -it -d -p 10080:8080 --name esp10-moodprism 192.168.160.99:5000/esp10-moodprism'	 
	             }
		 }
	   }
	}*/
        stage('clone dashboard'){
	   steps{
	        git branch: 'master',
			credentialsId: '8ea02772-3967-4797-9b78-2523260766bc'
		   	url: 'git@github.com/MoodPrism/dashboard.git' 
	   } 
        }
    }
}
