pipeline {
	agent {docker {image 'maven:3.3.3'}}
	
    stages {
        /*stage('Clean') {
	    steps {
               sh "mvn -f moodprism/pom.xml clean test"
            }
        }*/
        stage('Test') {
            steps {
                sh "mvn -f  moodprism/pom.xml test"
            }
        }
        stage('Package') {
            steps {
                sh "mvn -f  moodprism/pom.xml package"
            }
        }
    }
}
